# Generated by Django 5.0.3 on 2024-05-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=50)),
                ('character_class', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField()),
                ('background', models.CharField(max_length=100)),
                ('alignment', models.CharField(max_length=20)),
                ('experience_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveIntegerField()),
                ('dexterity', models.PositiveIntegerField()),
                ('constitution', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('wisdom', models.PositiveIntegerField()),
                ('charisma', models.PositiveIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.character')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.character')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.BooleanField(default=False)),
                ('modifier', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.character')),
            ],
        ),
    ]
